class LocationsPool {
private:
	static bool locationPoolInitiated;
public:
	static LocationsPool getInstance();
	int lenpool();
	void delete_and_clear_pool();
	char isThereASiegeHere(int cursite);
	int isThisPlaceHighSecurity(int cursite);
	void isThereASiegeHere(int cursite, char newCondition);
	void isThisPlaceHighSecurity(int cursite, int newCondition);
	char getLocationType(int cursite);
	short getSiegeType(int cursite);
	short getSiegeEscalationState(int cursite);
	int getRentingType(int cursite);
	void initSite(int loc);
	void eraseAndReplaceGraffiti(int cursite, int locx, int locy, int locz);
	string getLocationName(int cursite);
	int getLocationCity(int cursite);
	void hideCCSSafehouses();
	void addHeat(int cursite, int heat);
	void findAllLootTypes(vector<bool>& havetype, vector<int>& loottypeindex, const vector<string>& dox);
	bool isLocationMapped(int cursite);
	bool isLocationHidden(int cursite);
	void setLocationMappedAndUnhidden(int cursite);
	string getLocationNameWithGetnameMethod(int cursite, signed char a, bool b);
	string getLocationNameWithGetnameMethod(int cursite, signed char a);
	void removeTank(int cursite);
	void addSiegeKill(int cursite);
	int getCompoundWalls(int cursite);
	void setTimeUntilSiege(int cursite, int time);
	bool isNewRental(int cursite);
	void evictLCSFrom(int l);
	int isThisSiteClosed(int cursite);
	char doesThisPlaceNeedACar(int cursite);
	int findTravelLocation();
	int getLocationParent(int cursite);
	int deleteSpecialItem(int slot, vector<int> loottypeindex);
	void getAssetValues(long & weaponValue, long & armorValue, long & clipValue, long & lootValue);
	bool canBeFortified(int cursite);
	void initLocation(int cursite);
	void equipLoc(int, int);
	void stashThisLootHere(const string&, int);
	void stashThisWeaponHere(int itemindex, int shelter);
	void stashThisArmorHere(int itemindex, int shelter);
};
