
#include <includes.h>

#include <cursesAlternative.h>
#include <customMaps.h>
#include <constant_strings.h>
#include <gui_constants.h>
#include <set_color_support.h>
extern vector<Location *> location;
extern bool multipleCityMode;


Location* find_site_in_city(int site_type, int city)
{
   int i=find_site_index_in_city(site_type,city);
   if(i!=-1) return location[i];
   else return NULL;
}
int find_site_index_in_city(int site_type, int city)
{
   for(int i=0;i<len(location);i++)
      if(location[i]->type==site_type&&(!multipleCityMode||city==-1||location[i]->city==city))
         return i;
   return -1;
}
int find_site_index_in_same_city(int site_type, int site_index)
{
   int city=-1;
   if(site_index>=0) city=location[site_index]->city;
   return find_site_index_in_city(site_type,city);
}

void make_classic_world(bool hasmaps)
{
	Location* city = NULL;
	Location* district = NULL;
	Location* site = NULL;
	//int id = 0;
	if (city) district = city->addchild(SITE_DOWNTOWN);
	else location.push_back(district = new Location(SITE_DOWNTOWN));
	// = id++;
	district->area = 0;
	district->mapped = hasmaps; // for some reason this property isn't inherited by downtown locations so it's manually added for each one, need to debug why this happens
	site = district->addchild(SITE_RESIDENTIAL_APARTMENT_UPSCALE);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_GOVERNMENT_POLICESTATION);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_GOVERNMENT_COURTHOUSE);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_BUSINESS_BANK);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_GOVERNMENT_FIRESTATION);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_MEDIA_AMRADIO);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_MEDIA_CABLENEWS);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_BUSINESS_CIGARBAR);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_BUSINESS_LATTESTAND);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_BUSINESS_BARANDGRILL);
	// = id++;
	site->renting = RENTING_CCS;
	site->hidden = true;
	site->mapped = false;
	if (city) district = city->addchild(SITE_COMMERCIAL);
	else location.push_back(district = new Location(SITE_COMMERCIAL));
	// = id++;
	district->area = 0;
	site = district->addchild(SITE_BUSINESS_DEPTSTORE);
	// = id++;
	site = district->addchild(SITE_BUSINESS_PAWNSHOP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_HALLOWEEN);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CARDEALERSHIP);
	// = id++;
	if (city) district = city->addchild(SITE_UDISTRICT);
	else location.push_back(district = new Location(SITE_UDISTRICT));
	// = id++;
	district->area = 0;
	site = district->addchild(SITE_RESIDENTIAL_APARTMENT);
	// = id++;
	site = district->addchild(SITE_HOSPITAL_UNIVERSITY);
	// = id++;
	site = district->addchild(SITE_HOSPITAL_CLINIC);
	// = id++;
	site = district->addchild(SITE_LABORATORY_GENETIC);
	// = id++;
	site = district->addchild(SITE_LABORATORY_COSMETICS);
	// = id++;
	site = district->addchild(SITE_BUSINESS_VEGANCOOP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_JUICEBAR);
	// = id++;
	site = district->addchild(SITE_BUSINESS_INTERNETCAFE);
	// = id++;
	site = district->addchild(SITE_OUTDOOR_PUBLICPARK);
	// = id++;
	if (city) district = city->addchild(SITE_INDUSTRIAL);
	else location.push_back(district = new Location(SITE_INDUSTRIAL));
	// = id++;
	district->area = 0;
	site = district->addchild(SITE_RESIDENTIAL_SHELTER);
	// = id++;
	site->renting = RENTING_PERMANENT;
	site = district->addchild(SITE_INDUSTRY_WAREHOUSE);
	// = id++;
	site->renting = RENTING_PERMANENT;
	site->upgradable = true;
	site = district->addchild(SITE_RESIDENTIAL_TENEMENT);
	// = id++;
	site = district->addchild(SITE_INDUSTRY_POLLUTER);
	// = id++;
	site = district->addchild(SITE_INDUSTRY_SWEATSHOP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CRACKHOUSE);
	// = id++;
	site->upgradable = true;
	site = district->addchild(SITE_RESIDENTIAL_BOMBSHELTER);
	// = id++;
	site->renting = RENTING_CCS;
	site->hidden = true;
	if (city) district = city->addchild(SITE_OUTOFTOWN);
	else location.push_back(district = new Location(SITE_OUTOFTOWN));
	// = id++;
	district->area = 1;
	site = district->addchild(SITE_GOVERNMENT_PRISON);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_INTELLIGENCEHQ);
	// = id++;
	site = district->addchild(SITE_INDUSTRY_NUCLEAR);
	// = id++;
	site = district->addchild(SITE_CORPORATE_HEADQUARTERS);
	// = id++;
	site = district->addchild(SITE_CORPORATE_HOUSE);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_ARMYBASE);
	// = id++;
	site = district->addchild(SITE_OUTDOOR_BUNKER);
	// = id++;
	site->renting = RENTING_CCS;
	site->hidden = true;
	if (city) district = city->addchild(SITE_TRAVEL);
	else location.push_back(district = new Location(SITE_TRAVEL));
	// = id++;
	district->area = 1;
	site = district->addchild(SITE_GOVERNMENT_WHITE_HOUSE);
	// = id++;
}
void make_world(bool hasmaps)
{
	if (!multipleCityMode)
	{
		make_classic_world(hasmaps);
		return;
	}
	//MAKE LOCATIONS
	Location* city = NULL;
	Location* district = NULL;
	Location* site = NULL;
	//int id = 0;
	// Seattle
	location.push_back(city = new Location(SITE_CITY_SEATTLE));
	// = id++;
	if (city) district = city->addchild(SITE_DOWNTOWN);
	else location.push_back(district = new Location(SITE_DOWNTOWN));
	// = id++;
	district->area = 0;
	district->mapped = hasmaps; // for some reason this property isn't inherited by downtown locations so it's manually added for each one, need to debug why this happens
	site = district->addchild(SITE_RESIDENTIAL_APARTMENT_UPSCALE);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_GOVERNMENT_POLICESTATION);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_GOVERNMENT_COURTHOUSE);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_BUSINESS_BANK);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_GOVERNMENT_FIRESTATION);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_MEDIA_AMRADIO);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_BUSINESS_CIGARBAR);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_BUSINESS_LATTESTAND);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_BUSINESS_DEPTSTORE);
	// = id++;
	site->mapped = hasmaps;
	site = district->addchild(SITE_BUSINESS_BARANDGRILL);
	// = id++;
	site->renting = RENTING_CCS;
	site->hidden = true;
	site->mapped = false;
	if (city) district = city->addchild(SITE_UDISTRICT);
	else location.push_back(district = new Location(SITE_UDISTRICT));
	// = id++;
	district->area = 0;
	site = district->addchild(SITE_RESIDENTIAL_APARTMENT);
	// = id++;
	site = district->addchild(SITE_HOSPITAL_UNIVERSITY);
	// = id++;
	site = district->addchild(SITE_HOSPITAL_CLINIC);
	// = id++;
	site = district->addchild(SITE_LABORATORY_GENETIC);
	// = id++;
	site = district->addchild(SITE_LABORATORY_COSMETICS);
	// = id++;
	site = district->addchild(SITE_BUSINESS_VEGANCOOP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_JUICEBAR);
	// = id++;
	site = district->addchild(SITE_BUSINESS_INTERNETCAFE);
	// = id++;
	site = district->addchild(SITE_OUTDOOR_PUBLICPARK);
	// = id++;
	site = district->addchild(SITE_BUSINESS_HALLOWEEN);
	// = id++;
	if (city) district = city->addchild(SITE_INDUSTRIAL);
	else location.push_back(district = new Location(SITE_INDUSTRIAL));
	// = id++;
	district->area = 0;
	site = district->addchild(SITE_RESIDENTIAL_SHELTER);
	// = id++;
	site->renting = RENTING_PERMANENT;
	site = district->addchild(SITE_INDUSTRY_WAREHOUSE);
	// = id++;
	site->renting = RENTING_PERMANENT;
	site->upgradable = true;
	site = district->addchild(SITE_RESIDENTIAL_TENEMENT);
	// = id++;
	site = district->addchild(SITE_INDUSTRY_POLLUTER);
	// = id++;
	site = district->addchild(SITE_INDUSTRY_SWEATSHOP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CRACKHOUSE);
	// = id++;
	site->upgradable = true;
	site = district->addchild(SITE_BUSINESS_PAWNSHOP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CARDEALERSHIP);
	// = id++;
	if (city) district = city->addchild(SITE_OUTOFTOWN);
	else location.push_back(district = new Location(SITE_OUTOFTOWN));
	// = id++;
	district->area = 1;
	site = district->addchild(SITE_GOVERNMENT_PRISON);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_INTELLIGENCEHQ);
	// = id++;
	//site = district->addchild(SITE_INDUSTRY_NUCLEAR); 
	//// = id++;
	site = district->addchild(SITE_CORPORATE_HEADQUARTERS);
	// = id++;
	//site = district->addchild(SITE_CORPORATE_HOUSE); 
	//// = id++;
	site = district->addchild(SITE_GOVERNMENT_ARMYBASE);
	// = id++;
	// New York City
	location.push_back(city = new Location(SITE_CITY_NEW_YORK));
	// = id++;
	if (city) district = city->addchild(SITE_DOWNTOWN);
	else location.push_back(district = new Location(SITE_DOWNTOWN));
	// = id++;
	district->area = 0;
	strcpy(district->name, "Manhattan Island");
	strcpy(district->shortname, "Manhattan");
	//district->mapped = hasmaps;
	site = district->addchild(SITE_RESIDENTIAL_APARTMENT_UPSCALE);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_POLICESTATION);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_COURTHOUSE);
	// = id++;
	site = district->addchild(SITE_BUSINESS_BANK);
	// = id++;
	site = district->addchild(SITE_CORPORATE_HEADQUARTERS);
	// = id++;
	site = district->addchild(SITE_MEDIA_AMRADIO);
	// = id++;
	site = district->addchild(SITE_MEDIA_CABLENEWS);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CIGARBAR);
	// = id++;
	//site = district->addchild(SITE_CORPORATE_HOUSE); 
	//// = id++;
	//site = district->addchild(SITE_GOVERNMENT_INTELLIGENCEHQ); 
	//// = id++;
	site = district->addchild(SITE_OUTDOOR_PUBLICPARK);
	// = id++;
	site = district->addchild(SITE_BUSINESS_DEPTSTORE);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_PRISON);
	// = id++;
	if (city) district = city->addchild(SITE_UDISTRICT);
	else location.push_back(district = new Location(SITE_UDISTRICT));
	// = id++;
	district->area = 0;
	strcpy(district->name, "Brooklyn & Queens");
	strcpy(district->shortname, "Long Island");
	site = district->addchild(SITE_INDUSTRY_WAREHOUSE);
	// = id++;
	site->renting = RENTING_PERMANENT;
	site->upgradable = true;
	site = district->addchild(SITE_RESIDENTIAL_APARTMENT);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_FIRESTATION);
	// = id++;
	site = district->addchild(SITE_HOSPITAL_UNIVERSITY);
	// = id++;
	site = district->addchild(SITE_HOSPITAL_CLINIC);
	// = id++;
	site = district->addchild(SITE_BUSINESS_JUICEBAR);
	// = id++;
	site = district->addchild(SITE_BUSINESS_INTERNETCAFE);
	// = id++;
	site = district->addchild(SITE_INDUSTRY_POLLUTER);
	// = id++;
	site = district->addchild(SITE_LABORATORY_GENETIC);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_ARMYBASE);
	// = id++;
	site = district->addchild(SITE_RESIDENTIAL_BOMBSHELTER);
	// = id++;
	site->renting = RENTING_CCS;
	site->hidden = true;
	if (city) district = city->addchild(SITE_INDUSTRIAL);
	else location.push_back(district = new Location(SITE_INDUSTRIAL));
	// = id++;
	district->area = 0;
	strcpy(district->name, "The Bronx");
	strcpy(district->shortname, "The Bronx");
	site = district->addchild(SITE_RESIDENTIAL_SHELTER);
	// = id++;
	site->renting = RENTING_PERMANENT;
	site = district->addchild(SITE_RESIDENTIAL_TENEMENT);
	// = id++;
	site = district->addchild(SITE_INDUSTRY_POLLUTER);
	// = id++;
	site = district->addchild(SITE_INDUSTRY_SWEATSHOP);
	// = id++;
	site = district->addchild(SITE_LABORATORY_COSMETICS);
	// = id++;
	site = district->addchild(SITE_BUSINESS_VEGANCOOP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_PAWNSHOP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CARDEALERSHIP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CRACKHOUSE);
	// = id++;
	site->upgradable = true;
	site = district->addchild(SITE_OUTDOOR_PUBLICPARK);
	// = id++;
	if (city) district = city->addchild(SITE_OUTOFTOWN);
	else location.push_back(district = new Location(SITE_OUTOFTOWN));
	// = id++;
	district->area = 1;
	site = district->addchild(SITE_INDUSTRY_NUCLEAR);
	// = id++;
	// Los Angeles
	location.push_back(city = new Location(SITE_CITY_LOS_ANGELES));
	// = id++;
	if (city) district = city->addchild(SITE_DOWNTOWN);
	else location.push_back(district = new Location(SITE_DOWNTOWN));
	// = id++;
	district->area = 0;
	//district->mapped = hasmaps;
	site = district->addchild(SITE_RESIDENTIAL_SHELTER);
	// = id++;
	site->renting = RENTING_PERMANENT;
	site = district->addchild(SITE_RESIDENTIAL_APARTMENT);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_POLICESTATION);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_COURTHOUSE);
	// = id++;
	site = district->addchild(SITE_BUSINESS_BANK);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_FIRESTATION);
	// = id++;
	site = district->addchild(SITE_CORPORATE_HEADQUARTERS);
	// = id++;
	site = district->addchild(SITE_HOSPITAL_UNIVERSITY);
	// = id++;
	site = district->addchild(SITE_BUSINESS_DEPTSTORE);
	// = id++;
	if (city) district = city->addchild(SITE_UDISTRICT);
	else location.push_back(district = new Location(SITE_UDISTRICT));
	// = id++;
	district->area = 0;
	strcpy(district->name, "Greater Hollywood");
	strcpy(district->shortname, "Hollywood");
	site = district->addchild(SITE_RESIDENTIAL_APARTMENT_UPSCALE);
	// = id++;
	site = district->addchild(SITE_BUSINESS_VEGANCOOP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_HALLOWEEN);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CIGARBAR);
	// = id++;
	//site = district->addchild(SITE_MEDIA_CABLENEWS); 
	//// = id++;
	site = district->addchild(SITE_MEDIA_AMRADIO);
	// = id++;
	site = district->addchild(SITE_OUTDOOR_PUBLICPARK);
	// = id++;
	site = district->addchild(SITE_CORPORATE_HOUSE);
	// = id++;
	if (city) district = city->addchild(SITE_INDUSTRIAL);
	else location.push_back(district = new Location(SITE_INDUSTRIAL));
	// = id++;
	district->area = 0;
	strcpy(district->name, "Seaport Area");
	strcpy(district->shortname, "Seaport");
	site = district->addchild(SITE_INDUSTRY_WAREHOUSE);
	// = id++;
	site->renting = RENTING_PERMANENT;
	site->upgradable = true;
	site = district->addchild(SITE_RESIDENTIAL_TENEMENT);
	// = id++;
	site = district->addchild(SITE_HOSPITAL_CLINIC);
	// = id++;
	site = district->addchild(SITE_LABORATORY_GENETIC);
	// = id++;
	site = district->addchild(SITE_LABORATORY_COSMETICS);
	// = id++;
	site = district->addchild(SITE_INDUSTRY_POLLUTER);
	// = id++;
	site = district->addchild(SITE_BUSINESS_PAWNSHOP);
	// = id++;
	site = district->addchild(SITE_INDUSTRY_SWEATSHOP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CARDEALERSHIP);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CRACKHOUSE);
	// = id++;
	site->upgradable = true;
	if (city) district = city->addchild(SITE_OUTOFTOWN);
	else location.push_back(district = new Location(SITE_OUTOFTOWN));
	// = id++;
	district->area = 1;
	strcpy(district->name, "Outskirts & Orange County");
		site = district->addchild(SITE_GOVERNMENT_PRISON);
	// = id++;
	//site = district->addchild(SITE_GOVERNMENT_INTELLIGENCEHQ); 
	// = id++;
	site = district->addchild(SITE_INDUSTRY_NUCLEAR);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_ARMYBASE);
	// = id++;
	site = district->addchild(SITE_OUTDOOR_BUNKER);
	// = id++;
	site->renting = RENTING_CCS;
	site->hidden = true;
	// Washington, DC
	location.push_back(city = new Location(SITE_CITY_WASHINGTON_DC));
	// = id++;
	if (city) district = city->addchild(SITE_DOWNTOWN);
	else location.push_back(district = new Location(SITE_DOWNTOWN));
	// = id++;
	district->area = 0;
	strcpy(district->name, "Downtown");
	//district->mapped = hasmaps;
	site = district->addchild(SITE_GOVERNMENT_POLICESTATION);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_FIRESTATION);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_COURTHOUSE);
	// = id++;
	site = district->addchild(SITE_BUSINESS_BANK);
	// = id++;
	site = district->addchild(SITE_BUSINESS_CARDEALERSHIP);
	// = id++;
	site = district->addchild(SITE_HOSPITAL_CLINIC);
	// = id++;
	site = district->addchild(SITE_HOSPITAL_UNIVERSITY);
	// = id++;
	site = district->addchild(SITE_BUSINESS_DEPTSTORE);
	// = id++;
	site = district->addchild(SITE_RESIDENTIAL_SHELTER);
	// = id++;
	site->renting = RENTING_PERMANENT;
	if (city) district = city->addchild(SITE_UDISTRICT);
	else location.push_back(district = new Location(SITE_UDISTRICT));
	// = id++;
	district->area = 0;
	strcpy(district->name, "National Mall");
	strcpy(district->shortname, "Mall");
	site = district->addchild(SITE_OUTDOOR_PUBLICPARK);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_WHITE_HOUSE);
	// = id++;
	if (city) district = city->addchild(SITE_OUTOFTOWN);
	else location.push_back(district = new Location(SITE_OUTOFTOWN));
	// = id++;
	district->area = 1;
	strcpy(district->name, "Arlington");
	site = district->addchild(SITE_GOVERNMENT_PRISON);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_INTELLIGENCEHQ);
	// = id++;
	site = district->addchild(SITE_GOVERNMENT_ARMYBASE);
	// = id++;
	//location.push_back(city = new Location(SITE_CITY_CHICAGO));
	//// = id++;;
	//location.push_back(city = new Location(SITE_CITY_DETROIT));
	//// = id++;;
	//location.push_back(city = new Location(SITE_CITY_ATLANTA));
	//// = id++;;
	//location.push_back(city = new Location(SITE_CITY_MIAMI));
	//// = id++;;
}
