
const string tag_value = "value";
const string tag_attribute = "attribute";
const string tag_skill = "skill";

void printEscapeEngageInfo();
void printEscapeEngageInfoFooter(const bool cameras, const bool traps);
void logDefeat();
void printConquerTextCCS(const int ccs_siege_kills, const int ccs_kills);
void printConquerText(const bool police);

void printBrokenLawsFooter(const bool kidnapped, const int typenum);
void printHarboringFugitive();
void printBrokenLawsHeader(const char underAttack, const short escalation);
void printBurnedFlag(const int flagLaw);
void printHireIllegal(const bool lawStatus);
void printReleaseKidnapped(const string kname, const int kidnapped);
void printCCSRaidSafehouse();
void printCorpSiegeWarning(const int sleeper, const string locationName);
void corporateSiegePrint(const string lname);
void printCCSCarbomb();
void printCCSRaid(const string lname);
void printEveryoneInjuredHeader();
void printInjuredList(const vector<pair<string, int> > injuredList);
void printKillList(const vector<pair<string, int> > killList);
void printCCSSleeperWarning(const string lname);
void printJetBombers();
void printTankArrival(const bool tank_traps);
void printSWATArrival();
void printPoliceSiegeHeader(const string lname);
void printPoliceSleeperWarning(const string locationName, const int siegeEscalationState);
void printPoliceSiegeEmptyHeader(const string lname);
void printCorpseRecoveredByPolice(const string corpse, const int y);
void printKidnapRecoveredByPolice(const string kidnap, const int y);
void printSpecificCrime(const Lawflags crime);
void printMostSeriousCrime(const bool breakercount[LAWFLAGNUM]);
void printWantedFor();
void printRehab();
void printEveryoneHereIsDead(const string lname);
void printBusinessFrontTaken();
void printCompoundDismantled();
void printPrintingpressDismantled();
void printMoneyConfiscated(const int confiscated);
void printFundsIntact();
void printLiberalsTakenToPolice(const int pcount);
void printSingleLiberalTaken(const string pname, const string pcname);
void printKidnapFreed();
void printSingleKidnapFreed(const string kname);
void printTheyConfiscateEverything(const int siege, const int escalationState);
void printConquerTextCCS(const int ccs_siege_kills, const int ccs_kills);
void printCorpseRecovery(const int y, const string name);
void printKidnapRescue(const int y, const string name);
void printFiremenSiegeEmpty(const string locationName);
void printFiremenRaid2();
void printFiremenRaid(const string loc);
void printFiremenSiegeEmpty(const bool printingPress, const bool businessFront);
void printCIASiegeWarning(const string locationName);
void printCIASiege(const string locationName, const bool hasCameras, const bool hasAGenerator);
void printRadioHicksSiege(const int l);
void printCableHicksSiege(const int l);
void printFiremenSiege(const bool sleeper, const int l);
void printReporterEnteredCompound(const string repname);
void printThePoliceCutLights(const bool clearformess);
void printReporterDuringSiege(const string repname, const string name, const int segmentpower);
void printShotBySniper(const string targname);
void printMissedBySniper(const string targname);
void printWasKilledInBombing(const string targname);
void printNarrowlyAvoidsDeath(const string targname);
void printNoOneIsHurt(const bool clearformess);
void printCONST_THE_LIGHTS_FADE_AND_ALL_IS_DARK(const bool clearformess);
void printCONST_THE_GENERATOR_HAS_BEEN_DESTROYED(const bool clearformess);
void printCONST_THERE_S_NOTHING_LEFT_BUT_SMOKING_WRECKAGE(const bool clearformess);
void printCONST_THE_ANTI_AIRCRAFT_GUN_TAKES_A_DIRECT_HIT(const bool clearformess);
void printCONST_EXPLOSIONS_ROCK_THE_COMPOUND(const bool clearformess);
void printCONST_A_SKILLED_PILOT_GETS_THROUGH(const bool clearformess);
void printCONST_IT_S_ALL_OVER_THE_TV_EVERYONE_IN_THE_LIBERAL_CRIME_SQUAD_GAINS_20_JUICE(const bool clearformess);
void printCONST_HIT_ONE_OF_THE_BOMBERS_SLAMS_INTO_TO_THE_GROUND(const bool clearformess);
void printCONST_YOU_DIDN_T_SHOOT_ANY_DOWN_BUT_YOU_VE_MADE_THEM_THINK_TWICE(const bool clearformess);
void printCONST_THE_THUNDER_OF_THE_ANTI_AIRCRAFT_GUN_SHAKES_THE_COMPOUND(const bool clearformess);
void printCONST_YOU_HEAR_PLANES_STREAK_OVERHEAD(const bool clearformess);
void printConservativesRaidedUnoccupiedSafehouse(const string locname);
void printCorpseRecovered(const string pname, const int y);
void printLiberalRescued(const string pname, const int y);
void printReflectOnYourConJudgement();
void printSallyForthSiege();
void printSallyForthFooter();
void printYoureFree();
void printSiegeIsBroken();
void printSiegeOptions(const int partysize, const short party_status);
void printLocationName(const string loc);
void printTanksMoveToEntrance(const bool clearformess);
void printEngineersRemoveTankTrap(const bool clearformess);
void logADayPasses();
void printYourLiberalsAreStarving(const bool clearformess);
void printHasStarvedToDeath(const string pname, const bool clearformess);
void printTheCopsAreComing(const bool clearformess);
void printYouHaveEscaped();
void printEscapeEngageInfo();
void printEscapeEngageInfoFooter(const bool cameras, const bool traps);
void logDefeat();
void printConquerText(const bool police);
int print_character_info(const int c, const int party_status);
int print_character_info(const int c, const int party_status);