




/*
	File created by Chris Johnson.
	These were previously all in game.cpp.

	This file includes all the the enums, defines, and included headers required globally by all components.

	All code released under GNU GPL.
*/
#pragma once

#include "includes.h"

using namespace std;


const int BIT1 = (1 << 0);
const int BIT2 = (1 << 1);
const int BIT3 = (1 << 2);
const int BIT4 = (1 << 3);
const int BIT5 = (1 << 4);
const int BIT6 = (1 << 5);
const int BIT7 = (1 << 6);
const int BIT8 = (1 << 7);
const int BIT9 = (1 << 8);
const int BIT10 = (1 << 9);
const int BIT11 = (1 << 10);
const int BIT12 = (1 << 11);
const int BIT13 = (1 << 12);
const int BIT14 = (1 << 13);
const int BIT15 = (1 << 14);
const int BIT16 = (1 << 15);
const int BIT17 = (1 << 16);
const int BIT18 = (1 << 17);
const int BIT19 = (1 << 18);
const int BIT20 = (1 << 19);
const int BIT21 = (1 << 20);
const int BIT22 = (1 << 21);
const int BIT23 = (1 << 22);
const int BIT24 = (1 << 23);
const int BIT25 = (1 << 24);
const int BIT26 = (1 << 25);
const int BIT27 = (1 << 26);
const int BIT28 = (1 << 27);
const int BIT29 = (1 << 28);
const int BIT30 = (1 << 29);
const int BIT31 = (1 << 30);
const int BIT32 = (1 << 31);
const int MAX_PATH_SIZE = 2048;
const int RNG_SIZE = 4;

long LCSrandom(long max);
/* Determine size of vectors and any other container that implements the size() function.
This basically includes all types of containers except for the C++11 std::forward_list. */
template <class Container> inline long len(const Container& x)
{
	return x.size();
}
/* Determine array size in pickrandom() and various functions throughout the code.
Only works on actual arrays, not on vectors or other containers. */
template <typename T, size_t N> inline long len(const T(&x)[N])
{
	return N;
}
/* Override of the prior function for null-terminated C-strings as char arrays.
This override allows pickrandom() to pick a random character from a C-string we have as a char array. */
template <size_t N> inline long len(const char(&x)[N])
{
	return strlen(x);
}
/* Override of the prior function for null-terminated C-strings as char pointers.
This override allows pickrandom() to pick a random character from a C-string we have as a char pointer. */
inline long len(const char* x)
{
	return strlen(x);
}
/* Override for when it doesn't work with const in front of the char*
(compilers are weird about template function overrides) */
inline long len(char* x)
{
	return strlen(x);
}
/* Pick a random element from a vector/deque/map/std::string/C++11 std::array/etc. (e.g. a random string from a vector of strings).
It works on any container class that implements the [] operator, size() function, and value_type typename.
This doesn't work if the vector/deque/map/std::string/C++11 std::array/etc. has zero elements. */
template <class Container> inline typename Container::value_type& pickrandom(const Container& x)
{
	return const_cast<typename Container::value_type&>(x[LCSrandom(len(x))]);
}
/* Pick a random element from an array (e.g. a random string from an array of strings).
This doesn't work if the array has zero elements. */
template <typename T, size_t N> inline T& pickrandom(const T(&x)[N])
{
	return const_cast<T&>(x[LCSrandom(len(x))]);
}
/* Pick a random element from a C-string.
Returns '\x0' (null character) for empty string. */
inline char& pickrandom(const char* x)
{
	return const_cast<char&>(x[LCSrandom(len(x))]);
}
/* Override for when it doesn't work with const in front of the char*
(compilers are weird about template function overrides) */
inline char& pickrandom(char* x)
{
	return x[LCSrandom(len(x))];
}
/* Deletes a specified pointer and sets it to NULL. */
template <typename T> inline void delete_and_nullify(T* &o)
{
	delete o;
	o = NULL;
}
/* Deletes and removes a specified pointer from a container. */
template <class Container> inline void delete_and_remove(Container& c, int i)
{
	if (i <= -1) return; // check for invalid index, and don't delete anything in this case
	delete c[i];
	c.erase(c.begin() + i);
}
/* Deletes and removes a specified pointer from 2 containers it's in.
c1 and c2 must not be the same container! */
template <class Container> inline void delete_and_remove(Container& c1, int i1, Container& c2, int i2)
{
	if (i1 <= -1 || i2 <= -1) return; // check for invalid index, and don't delete anything in this case
	if (c1[i1] == c2[i2])
	{ // it's the same pointer, so just delete it once, then remove it from both containers
		delete_and_remove(c1, i1);
		if (c1 != c2 || i1 != i2) c2.erase(c2.begin() + i2); // remove it from 2nd location, unless 2nd location is identical to 1st location
	}
	else
	{ // it's 2 different pointers, so delete them both and remove them from both containers
		delete_and_remove(c1, i1);
		delete_and_remove(c2, i2);
	}
}
/* Deletes and removes all pointers in a container. */
template <class Container> inline void delete_and_clear(Container& c)
{
	while (len(c))
	{
		delete c.back();
		c.pop_back();
	}
}
/* Deletes and removes all pointers that 2 containers have in common. */
template <class Container> inline void delete_and_clear(Container& c1, Container& c2)
{
	for (int i1 = len(c1) - 1; i1 >= 0; i1--)
		for (int i2 = len(c2) - 1; i2 >= 0; i2--)
			if (c1[i1] == c2[i2]) delete_and_remove(c1, i1, c2, i2);
}



#define CH_USE_CP437




enum Activity
{
	ACTIVITY_NONE,
	ACTIVITY_VISIT,
	ACTIVITY_HOSTAGETENDING,
	ACTIVITY_TROUBLE,
	ACTIVITY_GRAFFITI,
	ACTIVITY_COMMUNITYSERVICE,
	ACTIVITY_SELL_ART,
	ACTIVITY_SELL_MUSIC,
	ACTIVITY_SELL_TSHIRTS,
	ACTIVITY_DONATIONS,
	ACTIVITY_SELL_DRUGS,
	ACTIVITY_PROSTITUTION,
	ACTIVITY_POLLS,
	ACTIVITY_CCFRAUD,
	ACTIVITY_DOS_RACKET,
	ACTIVITY_DOS_ATTACKS,
	ACTIVITY_HACKING,
	ACTIVITY_REPAIR_ARMOR,
	ACTIVITY_MAKE_ARMOR,
	ACTIVITY_STEALCARS,
	ACTIVITY_WHEELCHAIR,
	ACTIVITY_BURY,
	ACTIVITY_WRITE_BLOG,
	ACTIVITY_WRITE_LETTERS,
	ACTIVITY_WRITE_GUARDIAN,
	ACTIVITY_TEACH_POLITICS,
	ACTIVITY_TEACH_FIGHTING,
	ACTIVITY_TEACH_COVERT,
	ACTIVITY_STUDY_DEBATING,
	ACTIVITY_STUDY_MARTIAL_ARTS,
	ACTIVITY_STUDY_DRIVING,
	ACTIVITY_STUDY_PSYCHOLOGY,
	ACTIVITY_STUDY_FIRST_AID,
	ACTIVITY_STUDY_LAW,
	ACTIVITY_STUDY_DISGUISE,
	ACTIVITY_STUDY_SCIENCE,
	ACTIVITY_STUDY_BUSINESS,
	ACTIVITY_STUDY_GYMNASTICS,
	ACTIVITY_STUDY_MUSIC,
	ACTIVITY_STUDY_ART,
	ACTIVITY_STUDY_TEACHING,
	ACTIVITY_STUDY_WRITING,
	ACTIVITY_STUDY_LOCKSMITHING,
	ACTIVITY_STUDY_COMPUTERS,
	ACTIVITY_STUDY_FENCING,
	ACTIVITY_STUDY_WEAVING,
	ACTIVITY_STUDY_RELIGION,
	ACTIVITY_STUDY_CLUB,
	ACTIVITY_STUDY_STREETSENSE,
	ACTIVITY_STUDY_THROWING,
	ACTIVITY_STUDY_STEALTH,
	ACTIVITY_STUDY_SEDUCTION,
	ACTIVITY_CLINIC,
	ACTIVITY_HEAL,
	ACTIVITY_SLEEPER_LIBERAL,
	ACTIVITY_SLEEPER_CONSERVATIVE,
	ACTIVITY_SLEEPER_SPY,
	ACTIVITY_SLEEPER_RECRUIT,
	ACTIVITY_SLEEPER_SCANDAL,
	ACTIVITY_SLEEPER_EMBEZZLE,
	ACTIVITY_SLEEPER_STEAL,
	ACTIVITY_SLEEPER_JOINLCS,
	ACTIVITY_RECRUITING,
	ACTIVITY_AUGMENT,
	ACTIVITYNUM
};



const int ENCMAX = 18;
// ENCMAX _HAS_ to be 26 or less, or else there aren't enough letters


enum GameModes
{
	GAMEMODE_TITLE,
	GAMEMODE_BASE,
	GAMEMODE_SITE,
	GAMEMODE_CHASECAR,
	GAMEMODE_CHASEFOOT
};


enum Laws
{
	LAW_STALIN = -2, // not a real law: this is -2 and is actually calculated based on views >=0 and <VIEWNUM-3
	LAW_MOOD, // not a real law: this is -1 and is likewise calculated based on views >=0 and <VIEWNUM-3
	LAW_ABORTION, // law #0, the first one that is actually in the law[] array
	LAW_ANIMALRESEARCH,
	LAW_POLICEBEHAVIOR,
	LAW_PRIVACY,
	LAW_DEATHPENALTY,
	LAW_NUCLEARPOWER,
	LAW_POLLUTION,
	LAW_LABOR,
	LAW_GAY,
	LAW_CORPORATE,
	LAW_FREESPEECH,
	LAW_FLAGBURNING,
	LAW_GUNCONTROL,
	LAW_TAX,
	LAW_WOMEN,
	LAW_CIVILRIGHTS,
	LAW_DRUGS,
	LAW_IMMIGRATION,
	LAW_ELECTIONS,
	LAW_MILITARY,
	LAW_PRISONS,
	LAW_TORTURE,
	LAWNUM
};



//#ifdef	NEWENCOUNTER_CPP
// newencounter.cpp

#include "../creature/newcreature.h"
#include "../locations/locations.h"

#include "../locations/locationsPool.h"

extern coordinatest loc_coord;
extern short lawList[LAWNUM];
extern short mode;
extern short postalarmtimer;
extern short siteonfire;
extern short sitetype;
extern siteblockst levelmap[MAPX][MAPY][MAPZ];


void fillEncounter(CreatureTypes c, int numleft);
void emptyEncounter();
map<int, vector<int> > locationsSpawners = {
	map<int, vector<int> >::value_type(SITE_BUSINESS_JUICEBAR,{
	CREATURE_TEENAGER, 10,
	CREATURE_JUDGE_LIBERAL, 1,
	CREATURE_COLLEGESTUDENT, 10,
	CREATURE_MUSICIAN, 2,
	CREATURE_MATHEMATICIAN, 1,
	CREATURE_TEACHER, 1,
	CREATURE_HSDROPOUT, 1,
	CREATURE_ENGINEER, 1,
	CREATURE_FASTFOODWORKER, 1,
	CREATURE_BAKER, 1,
	CREATURE_BARISTA, 1,
	CREATURE_BARTENDER, 1,
	CREATURE_TELEMARKETER, 1,
	CREATURE_CARSALESMAN, 1,
	CREATURE_OFFICEWORKER, 1,
	CREATURE_MAILMAN, 1,
	CREATURE_CHEF, 1,
	CREATURE_NURSE, 1,
	CREATURE_AMATEURMAGICIAN, 1,
	CREATURE_HIPPIE, 6,
	CREATURE_CRITIC_ART, 1,
	CREATURE_CRITIC_MUSIC, 1,
	CREATURE_AUTHOR, 1,
	CREATURE_JOURNALIST, 1,
	CREATURE_SOCIALITE, 2,
	CREATURE_PROGRAMMER, 1,
	CREATURE_RETIREE, 1,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_CAMERAMAN, 1,
	CREATURE_HAIRSTYLIST, 1,
	CREATURE_FASHIONDESIGNER, 1,
	CREATURE_CLERK, 1,
	CREATURE_THIEF, 1,
	CREATURE_ACTOR, 1,
	CREATURE_YOGAINSTRUCTOR, 1,
	CREATURE_MARTIALARTIST, 1,
	CREATURE_ATHLETE, 1,
	CREATURE_LOCKSMITH, 1
		}),
	map<int, vector<int> >::value_type(SITE_BUSINESS_CIGARBAR,{
	CREATURE_SCIENTIST_EMINENT, 1,
	CREATURE_CORPORATE_MANAGER, 30,
	CREATURE_COP, 5,
	CREATURE_JUDGE_CONSERVATIVE, 1,
	CREATURE_RADIOPERSONALITY, 1,
	CREATURE_NEWSANCHOR, 1,
	CREATURE_MILITARYOFFICER, 1,
	CREATURE_LAWYER, 15,
	CREATURE_DOCTOR, 10,
	CREATURE_PSYCHOLOGIST, 1,
	CREATURE_MUSICIAN, 1,
	CREATURE_ENGINEER, 10,
	CREATURE_BARTENDER, 10,
	CREATURE_FOOTBALLCOACH, 1,
	CREATURE_CRITIC_ART, 1,
	CREATURE_CRITIC_MUSIC, 1,
	CREATURE_AUTHOR, 1,
	CREATURE_JOURNALIST, 1,
	CREATURE_SOCIALITE, 2,
	CREATURE_RETIREE, 1,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_FASHIONDESIGNER, 1,
	CREATURE_THIEF, 1,
	CREATURE_ACTOR, 1,
	CREATURE_ATHLETE, 1,
	CREATURE_FIREFIGHTER, 1,
	CREATURE_LOCKSMITH, 1, }),
	map<int, vector<int> >::value_type(SITE_BUSINESS_CRACKHOUSE,{
	CREATURE_TEENAGER, 100,
	CREATURE_MUSICIAN, 1,
	CREATURE_MATHEMATICIAN, 1,
	CREATURE_HSDROPOUT, 30,
	CREATURE_BUM, 200,
	CREATURE_GANGMEMBER, 200,
	CREATURE_CRACKHEAD, 200,
	CREATURE_PROSTITUTE, 200,
	CREATURE_BIKER, 5,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_THIEF, 3,
	CREATURE_ACTOR, 1,
	CREATURE_JOURNALIST, 2 }
	),
	map<int, vector<int> >::value_type(SITE_GOVERNMENT_WHITE_HOUSE,{
	CREATURE_SCIENTIST_EMINENT, 1,
	CREATURE_WORKER_JANITOR, 2,
	CREATURE_WORKER_SECRETARY, 2,
	CREATURE_TEENAGER, 1,
	CREATURE_JUDGE_LIBERAL, 1,
	CREATURE_JUDGE_CONSERVATIVE, 1,
	CREATURE_AGENT, 2,
	CREATURE_MILITARYOFFICER, 3,
	CREATURE_LAWYER, 3,
	CREATURE_DOCTOR, 1,
	CREATURE_COLLEGESTUDENT, 1,
	CREATURE_TEACHER, 1,
	CREATURE_OFFICEWORKER, 5,
	CREATURE_FOOTBALLCOACH, 1,
	CREATURE_CHEF, 1,
	CREATURE_VETERAN, 1,
	CREATURE_JOURNALIST, 2,
	CREATURE_SOCIALITE, 1,
	CREATURE_PHOTOGRAPHER, 2,
	CREATURE_CAMERAMAN, 1,
	CREATURE_HAIRSTYLIST, 1,
	CREATURE_CLERK, 5,
	CREATURE_ACTOR, 1,
	CREATURE_ATHLETE, 1 }
	),
	map<int, vector<int> >::value_type(SITE_OUTDOOR_PUBLICPARK,{
	CREATURE_SECURITYGUARD, 5,
	CREATURE_SCIENTIST_LABTECH, 10,
	CREATURE_SCIENTIST_EMINENT, 1,
	CREATURE_CORPORATE_MANAGER, 10,
	CREATURE_WORKER_JANITOR, 5,
	CREATURE_WORKER_SECRETARY, 15,
	CREATURE_TEENAGER, 5,
	CREATURE_COP, 5,
	CREATURE_JUDGE_LIBERAL, 1,
	CREATURE_JUDGE_CONSERVATIVE, 1,
	CREATURE_AGENT, 1,
	CREATURE_RADIOPERSONALITY, 1,
	CREATURE_NEWSANCHOR, 1,
	CREATURE_MILITARYOFFICER, 1,
	CREATURE_LAWYER, 5,
	CREATURE_DOCTOR, 5,
	CREATURE_PSYCHOLOGIST, 1,
	CREATURE_NURSE, 5,
	CREATURE_SEWERWORKER, 1,
	CREATURE_COLLEGESTUDENT, 30,
	CREATURE_MUSICIAN, 5,
	CREATURE_MATHEMATICIAN, 5,
	CREATURE_TEACHER, 5,
	CREATURE_HSDROPOUT, 1,
	CREATURE_BUM, 1,
	CREATURE_GANGMEMBER, 1,
	CREATURE_CRACKHEAD, 1,
	CREATURE_PRIEST, 1,
	CREATURE_ENGINEER, 5,
	CREATURE_FASTFOODWORKER, 5,
	CREATURE_BAKER, 1,
	CREATURE_BARISTA, 10,
	CREATURE_BARTENDER, 1,
	CREATURE_TELEMARKETER, 5,
	CREATURE_CARSALESMAN, 3,
	CREATURE_OFFICEWORKER, 10,
	CREATURE_FOOTBALLCOACH, 1,
	CREATURE_PROSTITUTE, 1,
	CREATURE_MAILMAN, 1,
	CREATURE_GARBAGEMAN, 1,
	CREATURE_PLUMBER, 1,
	CREATURE_CHEF, 1,
	CREATURE_CONSTRUCTIONWORKER, 3,
	CREATURE_AMATEURMAGICIAN, 1,
	CREATURE_MERC, 1,
	CREATURE_SOLDIER, 1,
	CREATURE_VETERAN, 3,
	CREATURE_HIPPIE, 1,
	CREATURE_CRITIC_ART, 1,
	CREATURE_CRITIC_MUSIC, 1,
	CREATURE_AUTHOR, 1,
	CREATURE_JOURNALIST, 1,
	CREATURE_SOCIALITE, 1,
	CREATURE_BIKER, 1,
	CREATURE_TRUCKER, 1,
	CREATURE_TAXIDRIVER, 1,
	CREATURE_PROGRAMMER, 5,
	CREATURE_RETIREE, 3,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_CAMERAMAN, 1,
	CREATURE_HAIRSTYLIST, 1,
	CREATURE_FASHIONDESIGNER, 1,
	CREATURE_CLERK, 1,
	CREATURE_THIEF, 1,
	CREATURE_ACTOR, 1,
	CREATURE_YOGAINSTRUCTOR, 1,
	CREATURE_MARTIALARTIST, 1,
	CREATURE_ATHLETE, 1,
	CREATURE_FIREFIGHTER, 1,
	CREATURE_LOCKSMITH, 1 }
	),
	map<int, vector<int> >::value_type(SITE_BUSINESS_LATTESTAND,{
	CREATURE_SECURITYGUARD, 5,
	CREATURE_SCIENTIST_LABTECH, 10,
	CREATURE_SCIENTIST_EMINENT, 1,
	CREATURE_CORPORATE_MANAGER, 10,
	CREATURE_WORKER_JANITOR, 5,
	CREATURE_WORKER_SECRETARY, 15,
	CREATURE_TEENAGER, 5,
	CREATURE_COP, 5,
	CREATURE_JUDGE_LIBERAL, 1,
	CREATURE_JUDGE_CONSERVATIVE, 1,
	CREATURE_AGENT, 1,
	CREATURE_RADIOPERSONALITY, 1,
	CREATURE_NEWSANCHOR, 1,
	CREATURE_MILITARYOFFICER, 1,
	CREATURE_LAWYER, 5,
	CREATURE_DOCTOR, 5,
	CREATURE_PSYCHOLOGIST, 1,
	CREATURE_NURSE, 5,
	CREATURE_SEWERWORKER, 1,
	CREATURE_COLLEGESTUDENT, 30,
	CREATURE_MUSICIAN, 5,
	CREATURE_MATHEMATICIAN, 5,
	CREATURE_TEACHER, 5,
	CREATURE_HSDROPOUT, 1,
	CREATURE_BUM, 1,
	CREATURE_GANGMEMBER, 1,
	CREATURE_CRACKHEAD, 1,
	CREATURE_PRIEST, 1,
	CREATURE_ENGINEER, 5,
	CREATURE_FASTFOODWORKER, 5,
	CREATURE_BAKER, 1,
	CREATURE_BARISTA, 10,
	CREATURE_BARTENDER, 1,
	CREATURE_TELEMARKETER, 5,
	CREATURE_CARSALESMAN, 3,
	CREATURE_OFFICEWORKER, 10,
	CREATURE_FOOTBALLCOACH, 1,
	CREATURE_PROSTITUTE, 1,
	CREATURE_MAILMAN, 1,
	CREATURE_GARBAGEMAN, 1,
	CREATURE_PLUMBER, 1,
	CREATURE_CHEF, 1,
	CREATURE_CONSTRUCTIONWORKER, 3,
	CREATURE_AMATEURMAGICIAN, 1,
	CREATURE_MERC, 1,
	CREATURE_SOLDIER, 1,
	CREATURE_VETERAN, 3,
	CREATURE_HIPPIE, 1,
	CREATURE_CRITIC_ART, 1,
	CREATURE_CRITIC_MUSIC, 1,
	CREATURE_AUTHOR, 1,
	CREATURE_JOURNALIST, 1,
	CREATURE_SOCIALITE, 1,
	CREATURE_BIKER, 1,
	CREATURE_TRUCKER, 1,
	CREATURE_TAXIDRIVER, 1,
	CREATURE_PROGRAMMER, 5,
	CREATURE_RETIREE, 3,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_CAMERAMAN, 1,
	CREATURE_HAIRSTYLIST, 1,
	CREATURE_FASHIONDESIGNER, 1,
	CREATURE_CLERK, 1,
	CREATURE_THIEF, 1,
	CREATURE_ACTOR, 1,
	CREATURE_YOGAINSTRUCTOR, 1,
	CREATURE_MARTIALARTIST, 1,
	CREATURE_ATHLETE, 1,
	CREATURE_FIREFIGHTER, 1,
	CREATURE_LOCKSMITH, 1 }
	),
	map<int, vector<int> >::value_type(SITE_BUSINESS_VEGANCOOP,{
	CREATURE_TEENAGER, 5,
	CREATURE_JUDGE_LIBERAL, 1,
	CREATURE_COLLEGESTUDENT, 50,
	CREATURE_MUSICIAN, 20,
	CREATURE_MATHEMATICIAN, 1,
	CREATURE_TEACHER, 1,
	CREATURE_HSDROPOUT, 10,
	CREATURE_BUM, 1,
	CREATURE_HIPPIE, 50,
	CREATURE_CRITIC_ART, 1,
	CREATURE_CRITIC_MUSIC, 1,
	CREATURE_AUTHOR, 1,
	CREATURE_JOURNALIST, 1,
	CREATURE_RETIREE, 1,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_YOGAINSTRUCTOR, 2 }
	),
	map<int, vector<int> >::value_type(SITE_BUSINESS_INTERNETCAFE,{
	CREATURE_SCIENTIST_LABTECH, 5,
	CREATURE_CORPORATE_MANAGER, 3,
	CREATURE_TEENAGER, 15,
	CREATURE_LAWYER, 3,
	CREATURE_COLLEGESTUDENT, 25,
	CREATURE_MUSICIAN, 2,
	CREATURE_MATHEMATICIAN, 1,
	CREATURE_TEACHER, 5,
	CREATURE_ENGINEER, 15,
	CREATURE_DOCTOR, 1,
	CREATURE_BARISTA, 10,
	CREATURE_CARSALESMAN, 3,
	CREATURE_OFFICEWORKER, 15,
	CREATURE_WORKER_SECRETARY, 5,
	CREATURE_HIPPIE, 1,
	CREATURE_PROGRAMMER, 15,
	CREATURE_RETIREE, 5,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_CAMERAMAN, 1,
	CREATURE_CLERK, 1,
	CREATURE_LOCKSMITH, 1 }
	),
	map<int, vector<int> >::value_type(SITE_RESIDENTIAL_SHELTER,{
	CREATURE_WORKER_JANITOR, 5,
	CREATURE_TEENAGER, 20,
	CREATURE_MUSICIAN, 3,
	CREATURE_MATHEMATICIAN, 1,
	CREATURE_BUM, 200,
	CREATURE_GANGMEMBER, 5,
	CREATURE_CRACKHEAD, 50,
	CREATURE_PROSTITUTE, 10,
	CREATURE_AMATEURMAGICIAN, 1,
	CREATURE_HIPPIE, 1,
	CREATURE_NURSE, 5,
	CREATURE_BIKER, 1,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_THIEF, 5,
	CREATURE_ACTOR, 1, }
	),
	map<int, vector<int> >::value_type(SITE_RESIDENTIAL_TENEMENT,{
	CREATURE_SECURITYGUARD, 1,
	CREATURE_SCIENTIST_LABTECH, 1,
	CREATURE_WORKER_JANITOR, 3,
	CREATURE_WORKER_SECRETARY, 2,
	CREATURE_TEENAGER, 5,
	CREATURE_SEWERWORKER, 1,
	CREATURE_COLLEGESTUDENT, 1,
	CREATURE_MUSICIAN, 1,
	CREATURE_MATHEMATICIAN, 1,
	CREATURE_TEACHER, 1,
	CREATURE_HSDROPOUT, 3,
	CREATURE_BUM, 3,
	CREATURE_GANGMEMBER, 3,
	CREATURE_CRACKHEAD, 3,
	CREATURE_FASTFOODWORKER, 1,
	CREATURE_BARISTA, 1,
	CREATURE_BARTENDER, 1,
	CREATURE_TELEMARKETER, 1,
	CREATURE_CARSALESMAN, 1,
	CREATURE_OFFICEWORKER, 1,
	CREATURE_PROSTITUTE, 3,
	CREATURE_MAILMAN, 1,
	CREATURE_GARBAGEMAN, 1,
	CREATURE_CONSTRUCTIONWORKER, 1,
	CREATURE_AMATEURMAGICIAN, 1,
	CREATURE_HICK, 1,
	CREATURE_SOLDIER, 1,
	CREATURE_VETERAN, 2,
	CREATURE_HIPPIE, 1,
	CREATURE_BIKER, 1,
	CREATURE_TAXIDRIVER, 1,
	CREATURE_RETIREE, 1,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_HAIRSTYLIST, 1,
	CREATURE_CLERK, 1,
	CREATURE_THIEF, 1,
	CREATURE_ACTOR, 1,
	CREATURE_FIREFIGHTER, 1,
	CREATURE_LOCKSMITH, 1 }
	),
	map<int, vector<int> >::value_type(SITE_RESIDENTIAL_APARTMENT,{

	CREATURE_SECURITYGUARD, 1,
	CREATURE_SCIENTIST_LABTECH, 1,
	CREATURE_CORPORATE_MANAGER, 1,
	CREATURE_WORKER_JANITOR, 1,
	CREATURE_WORKER_SECRETARY, 1,
	CREATURE_TEENAGER, 3,
	CREATURE_COP, 1,
	CREATURE_LAWYER, 1,
	CREATURE_SEWERWORKER, 1,
	CREATURE_COLLEGESTUDENT, 1,
	CREATURE_MUSICIAN, 1,
	CREATURE_MATHEMATICIAN, 1,
	CREATURE_TEACHER, 1,
	CREATURE_PRIEST, 1,
	CREATURE_ENGINEER, 1,
	CREATURE_FASTFOODWORKER, 1,
	CREATURE_BAKER, 1,
	CREATURE_BARISTA, 1,
	CREATURE_BARTENDER, 1,
	CREATURE_TELEMARKETER, 1,
	CREATURE_CARSALESMAN, 1,
	CREATURE_OFFICEWORKER, 1,
	CREATURE_FOOTBALLCOACH, 1,
	CREATURE_MAILMAN, 1,
	CREATURE_DOCTOR, 1,
	CREATURE_PSYCHOLOGIST, 1,
	CREATURE_NURSE, 1,
	CREATURE_GARBAGEMAN, 1,
	CREATURE_PLUMBER, 1,
	CREATURE_CHEF, 1,
	CREATURE_CONSTRUCTIONWORKER, 1,
	CREATURE_AMATEURMAGICIAN, 1,
	CREATURE_SOLDIER, 1,
	CREATURE_VETERAN, 2,
	CREATURE_HIPPIE, 1,
	CREATURE_CRITIC_ART, 1,
	CREATURE_CRITIC_MUSIC, 1,
	CREATURE_AUTHOR, 1,
	CREATURE_JOURNALIST, 1,
	CREATURE_TAXIDRIVER, 1,
	CREATURE_PROGRAMMER, 1,
	CREATURE_RETIREE, 1,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_CAMERAMAN, 1,
	CREATURE_HAIRSTYLIST, 1,
	CREATURE_CLERK, 1,
	CREATURE_THIEF, 1,
	CREATURE_ACTOR, 1,
	CREATURE_YOGAINSTRUCTOR, 1,
	CREATURE_MARTIALARTIST, 1,
	CREATURE_ATHLETE, 1,
	CREATURE_FIREFIGHTER, 1,
	CREATURE_LOCKSMITH, 1 }
	),
	map<int, vector<int> >::value_type(SITE_RESIDENTIAL_APARTMENT_UPSCALE,{
	CREATURE_SCIENTIST_EMINENT, 1,
	CREATURE_CORPORATE_MANAGER, 5,
	CREATURE_WORKER_JANITOR, 5,
	CREATURE_WORKER_SECRETARY, 1,
	CREATURE_TEENAGER, 3,
	CREATURE_JUDGE_LIBERAL, 1,
	CREATURE_JUDGE_CONSERVATIVE, 1,
	CREATURE_RADIOPERSONALITY, 1,
	CREATURE_NEWSANCHOR, 1,
	CREATURE_LAWYER, 5,
	CREATURE_DOCTOR, 5,
	CREATURE_PSYCHOLOGIST, 1,
	CREATURE_NURSE, 1,
	CREATURE_COLLEGESTUDENT, 1,
	CREATURE_MUSICIAN, 1,
	CREATURE_PROSTITUTE, 3,
	CREATURE_MAILMAN, 1,
	CREATURE_CRITIC_ART, 1,
	CREATURE_CRITIC_MUSIC, 1,
	CREATURE_AUTHOR, 1,
	CREATURE_JOURNALIST, 1,
	CREATURE_SOCIALITE, 2,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_FASHIONDESIGNER, 1,
	CREATURE_THIEF, 1,
	CREATURE_ACTOR, 1,
	CREATURE_ATHLETE, 1,
	CREATURE_LOCKSMITH, 1 }
	),
	map<int, vector<int> >::value_type(SITE_LABORATORY_COSMETICS,{
	CREATURE_SCIENTIST_LABTECH, 10,
	CREATURE_SCIENTIST_EMINENT, 1,
	CREATURE_CORPORATE_MANAGER, 1,
	CREATURE_WORKER_JANITOR, 10,
	CREATURE_WORKER_SECRETARY, 10,
	CREATURE_OFFICEWORKER, 10 }
	),
	map<int, vector<int> >::value_type(SITE_INDUSTRY_NUCLEAR,{
	CREATURE_SCIENTIST_LABTECH, 10,
	CREATURE_SCIENTIST_EMINENT, 1,
	CREATURE_CORPORATE_MANAGER, 1,
	CREATURE_WORKER_JANITOR, 10,
	CREATURE_WORKER_SECRETARY, 10,
	CREATURE_OFFICEWORKER, 10 }
	),
	map<int, vector<int> >::value_type(SITE_LABORATORY_GENETIC,{
	CREATURE_SCIENTIST_LABTECH, 10,
	CREATURE_SCIENTIST_EMINENT, 1,
	CREATURE_CORPORATE_MANAGER, 1,
	CREATURE_DOCTOR, 1,
	CREATURE_WORKER_JANITOR, 10,
	CREATURE_WORKER_SECRETARY, 10,
	CREATURE_OFFICEWORKER, 10 }
	),
	map<int, vector<int> >::value_type(SITE_GOVERNMENT_POLICESTATION,{
	CREATURE_SCIENTIST_LABTECH, 1,
	CREATURE_CORPORATE_MANAGER, 1,
	CREATURE_WORKER_JANITOR, 50,
	CREATURE_WORKER_SECRETARY, 1,
	CREATURE_TEENAGER, 5,
	CREATURE_JUDGE_LIBERAL, 1,
	CREATURE_JUDGE_CONSERVATIVE, 1,
	CREATURE_AGENT, 1,
	CREATURE_RADIOPERSONALITY, 1,
	CREATURE_NEWSANCHOR, 1,
	CREATURE_MILITARYOFFICER, 1,
	CREATURE_LAWYER, 1,
	CREATURE_DOCTOR, 1,
	CREATURE_PSYCHOLOGIST, 1,
	CREATURE_NURSE, 1,
	CREATURE_SEWERWORKER, 1,
	CREATURE_COLLEGESTUDENT, 1,
	CREATURE_MUSICIAN, 1,
	CREATURE_MATHEMATICIAN, 1,
	CREATURE_TEACHER, 1,
	CREATURE_HSDROPOUT, 10,
	CREATURE_BUM, 10,
	CREATURE_GANGMEMBER, 10,
	CREATURE_CRACKHEAD, 10,
	CREATURE_PRIEST, 5,
	CREATURE_ENGINEER, 1,
	CREATURE_FASTFOODWORKER, 1,
	CREATURE_BAKER, 1,
	CREATURE_BARISTA, 1,
	CREATURE_BARTENDER, 1,
	CREATURE_TELEMARKETER, 1,
	CREATURE_CARSALESMAN, 1,
	CREATURE_OFFICEWORKER, 1,
	CREATURE_FOOTBALLCOACH, 1,
	CREATURE_PROSTITUTE, 10,
	CREATURE_MAILMAN, 1,
	CREATURE_GARBAGEMAN, 1,
	CREATURE_PLUMBER, 1,
	CREATURE_CHEF, 1,
	CREATURE_CONSTRUCTIONWORKER, 1,
	CREATURE_AMATEURMAGICIAN, 1,
	CREATURE_HICK, 1,
	CREATURE_SOLDIER, 1,
	CREATURE_VETERAN, 2,
	CREATURE_HIPPIE, 1,
	CREATURE_CRITIC_ART, 1,
	CREATURE_CRITIC_MUSIC, 1,
	CREATURE_AUTHOR, 1,
	CREATURE_JOURNALIST, 1,
	CREATURE_SOCIALITE, 1,
	CREATURE_BIKER, 5,
	CREATURE_TRUCKER, 1,
	CREATURE_TAXIDRIVER, 1,
	CREATURE_PROGRAMMER, 1,
	CREATURE_NUN, 1,
	CREATURE_RETIREE, 1,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_CAMERAMAN, 1,
	CREATURE_HAIRSTYLIST, 1,
	CREATURE_FASHIONDESIGNER, 1,
	CREATURE_CLERK, 1,
	CREATURE_THIEF, 10,
	CREATURE_ACTOR, 1,
	CREATURE_YOGAINSTRUCTOR, 1,
	CREATURE_MARTIALARTIST, 1,
	CREATURE_ATHLETE, 1,
	CREATURE_LOCKSMITH, 5 }       //Forensic locksmiths
	),
	map<int, vector<int> >::value_type(SITE_GOVERNMENT_COURTHOUSE,{
	CREATURE_SCIENTIST_LABTECH, 1,
	CREATURE_SCIENTIST_EMINENT, 1,
	CREATURE_CORPORATE_MANAGER, 1,
	CREATURE_WORKER_JANITOR, 50,
	CREATURE_WORKER_SECRETARY, 50,
	CREATURE_TEENAGER, 1,
	CREATURE_JUDGE_LIBERAL, 20,
	CREATURE_JUDGE_CONSERVATIVE, 20,
	CREATURE_AGENT, 1,
	CREATURE_RADIOPERSONALITY, 1,
	CREATURE_NEWSANCHOR, 1,
	CREATURE_MILITARYOFFICER, 1,
	CREATURE_LAWYER, 200,
	CREATURE_PSYCHOLOGIST, 20,
	CREATURE_SEWERWORKER, 1,
	CREATURE_COLLEGESTUDENT, 1,
	CREATURE_MUSICIAN, 1,
	CREATURE_MATHEMATICIAN, 1,
	CREATURE_TEACHER, 1,
	CREATURE_HSDROPOUT, 1,
	CREATURE_BUM, 1,
	CREATURE_GANGMEMBER, 1,
	CREATURE_CRACKHEAD, 1,
	CREATURE_PRIEST, 1,
	CREATURE_ENGINEER, 1,
	CREATURE_FASTFOODWORKER, 1,
	CREATURE_BAKER, 1,
	CREATURE_BARISTA, 1,
	CREATURE_BARTENDER, 1,
	CREATURE_TELEMARKETER, 1,
	CREATURE_CARSALESMAN, 2,
	CREATURE_OFFICEWORKER, 50,
	CREATURE_FOOTBALLCOACH, 1,
	CREATURE_PROSTITUTE, 1,
	CREATURE_MAILMAN, 1,
	CREATURE_GARBAGEMAN, 1,
	CREATURE_PLUMBER, 1,
	CREATURE_CHEF, 1,
	CREATURE_CONSTRUCTIONWORKER, 1,
	CREATURE_AMATEURMAGICIAN, 1,
	CREATURE_HICK, 1,
	CREATURE_SOLDIER, 1,
	CREATURE_VETERAN, 2,
	CREATURE_HIPPIE, 1,
	CREATURE_CRITIC_ART, 1,
	CREATURE_CRITIC_MUSIC, 1,
	CREATURE_AUTHOR, 1,
	CREATURE_JOURNALIST, 1,
	CREATURE_SOCIALITE, 1,
	CREATURE_BIKER, 1,
	CREATURE_TRUCKER, 1,
	CREATURE_TAXIDRIVER, 1,
	CREATURE_PROGRAMMER, 1,
	CREATURE_NUN, 1,
	CREATURE_RETIREE, 1,
	CREATURE_PAINTER, 1,
	CREATURE_SCULPTOR, 1,
	CREATURE_DANCER, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_CAMERAMAN, 1,
	CREATURE_HAIRSTYLIST, 1,
	CREATURE_FASHIONDESIGNER, 1,
	CREATURE_CLERK, 1,
	CREATURE_THIEF, 3,
	CREATURE_ACTOR, 1,
	CREATURE_YOGAINSTRUCTOR, 1,
	CREATURE_MARTIALARTIST, 1,
	CREATURE_ATHLETE, 1,
	CREATURE_LOCKSMITH, 5 }
	),
	map<int, vector<int> >::value_type(SITE_GOVERNMENT_FIRESTATION,{
	CREATURE_WORKER_JANITOR, 5,
	CREATURE_WORKER_SECRETARY, 2,
	CREATURE_NURSE, 2,
	CREATURE_PRIEST, 5,
	CREATURE_JOURNALIST, 1,
	CREATURE_PHOTOGRAPHER, 1,
	CREATURE_FIREFIGHTER, 100 }
	),
	map<int, vector<int> >::value_type(SITE_GOVERNMENT_INTELLIGENCEHQ,{
	CREATURE_WORKER_JANITOR, 50,
	CREATURE_WORKER_SECRETARY, 50,
	CREATURE_GUARDDOG, 50,
	CREATURE_MATHEMATICIAN, 5,
	CREATURE_PROGRAMMER, 5,
	CREATURE_MILITARYOFFICER, 5 }


	),
	map<int, vector<int> >::value_type(SITE_GOVERNMENT_ARMYBASE,{
	CREATURE_SOLDIER, 750,
	CREATURE_GUARDDOG, 20,
	CREATURE_MILITARYPOLICE, 100,
	CREATURE_MILITARYOFFICER, 20,
	CREATURE_SEAL, 20 }


	),
	map<int, vector<int> >::value_type(SITE_INDUSTRY_SWEATSHOP,{
	CREATURE_CORPORATE_MANAGER, 5,
	CREATURE_WORKER_SWEATSHOP, 800 }

	),
	map<int, vector<int> >::value_type(SITE_INDUSTRY_POLLUTER,{
	CREATURE_CORPORATE_MANAGER, 1,
	CREATURE_WORKER_JANITOR, 10,
	CREATURE_WORKER_SECRETARY, 10 }
	),
	map<int, vector<int> >::value_type(SITE_CORPORATE_HEADQUARTERS,{

	CREATURE_CORPORATE_MANAGER, 20,
	CREATURE_WORKER_JANITOR, 20,
	CREATURE_WORKER_SECRETARY, 40,
	CREATURE_JUDGE_CONSERVATIVE, 1,
	CREATURE_LAWYER, 20,
	CREATURE_PRIEST, 1,
	CREATURE_OFFICEWORKER, 80,
	CREATURE_PROSTITUTE, 1 }


	),
	map<int, vector<int> >::value_type(SITE_CORPORATE_HOUSE,{
	CREATURE_WORKER_SERVANT, 30,
	CREATURE_WORKER_SECRETARY, 5,
	CREATURE_TEENAGER, 5,
	CREATURE_GENETIC, 1,
	CREATURE_LAWYER, 5,
	CREATURE_PRIEST, 1,
	CREATURE_PROSTITUTE, 1 }

	),
	map<int, vector<int> >::value_type(SITE_MEDIA_AMRADIO,{
	CREATURE_CORPORATE_MANAGER, 2,
	CREATURE_WORKER_JANITOR, 10,
	CREATURE_WORKER_SECRETARY, 10,
	CREATURE_RADIOPERSONALITY, 2,
	CREATURE_ENGINEER, 20,
	CREATURE_OFFICEWORKER, 40 }


	),
	map<int, vector<int> >::value_type(SITE_MEDIA_CABLENEWS,{
	CREATURE_CORPORATE_MANAGER, 5,
	CREATURE_WORKER_JANITOR, 20,
	CREATURE_WORKER_SECRETARY, 20,
	CREATURE_NEWSANCHOR, 2,
	CREATURE_ENGINEER, 40,
	CREATURE_OFFICEWORKER, 40,
	CREATURE_PHOTOGRAPHER, 5,
	CREATURE_CAMERAMAN, 5 }

	)
};
short getCurrentSite();
bool populateEncounter(const int type, int creaturearray[CREATURENUM], const char sec);
void conservatiseEncslot(const int encslot);
void conservatise(const int c);
void damage_creature(const int e);
vector<NameAndAlignment> getEncounterNameAndAlignment();
const string tag_value = "value";
const string tag_attribute = "attribute";
const string tag_skill = "skill";

//#endif//NEWENCOUNTER_CPP
//#endif// INCLUDES_H_INCLUDED
