#pragma once
enum ColorSetup {
	BLACK_ON_BLACK,
	BLACK_ON_BLACK_BRIGHT,
	BLACK_ON_WHITE,
	BLUE_ON_BLACK_BRIGHT,
	CYAN_ON_BLACK,
	CYAN_ON_BLACK_BRIGHT,
	GREEN_ON_BLACK,
	GREEN_ON_BLACK_BRIGHT,
	MAGENTA_ON_BLACK,
	MAGENTA_ON_BLACK_BRIGHT,
	RED_ON_BLACK,
	RED_ON_BLACK_BRIGHT,
	RED_ON_BLUE_BRIGHT,
	RED_ON_GREEN_BRIGHT,
	RED_ON_RED,
	WHITE_ON_BLACK,
	WHITE_ON_BLACK_BRIGHT,
	WHITE_ON_RED_BRIGHT,
	WHITE_ON_WHITE,
	WHITE_ON_WHITE_BRIGHT,
	YELLOW_ON_BLACK,
	YELLOW_ON_BLACK_BRIGHT,
	YELLOW_ON_RED,
	YELLOW_ON_RED_BRIGHT_BLINK
};
void set_color_easy(ColorSetup color);